### ISSUE TITLE
difference between Artery and Artery-C

### ISSUE THREAD

**Issue by yasminechibani** [anupama1990/Artery-C#1]
Hello, I really have a question please? what is the difference between Artery and Artery-C?

**Comment by anupama1990** [comment]
Artery-C uses Cellular V2X as the access layer and Artery is based on WLAN V2X

**Comment by yasminechibani** [comment]
on the other hand when we try to recover LTE with Artery we find the BlackICE example which does the same thing as Artery-C, right?
