### ISSUE TITLE
 installation Artery C problem 

### ISSUE THREAD

**Issue by yasminechibani** [anupama1990/Artery-C#2]
when i do cmake.. from Artery C i have this problem
[
![Capture d’écran du 2022-06-27 16-28-50](https://user-images.githubusercontent.com/108278499/175966979-f4308b4a-be8a-48c1-9db2-8737cdb5974a.png)
](url)

**Comment by riebl** [comment]
Looks like an incomplete repository clone. I suggest executing `git submodule update --init --recursive` to clone also all sub-repositories, including Veins.

**Comment by yasminechibani** [comment]
I got another error when I downloaded all sub-repositories,
![image](https://user-images.githubusercontent.com/108278499/177116665-9ede7a12-1f03-45e5-86c7-6fec3a71fefc.png)

**Comment by JohnnyMinho** [comment]
Hello I'm suffering from the same problem even though I already confirmed I have all the files and ran the git line you told to do.
